## name: Doom One
## author: NTBBloodbath / Doom Emacs
## upstream: https://github.com/NTBBloodbath/doom-one.nvim

selection_foreground    #282c34
selection_background    #51afef

background              #282c34
foreground              #bbc2cf

color0                  #1c1f24
color1                  #ff6c6b
color2                  #98be65
color3                  #da8548
color4                  #51afef
color5                  #c678dd
color6                  #46d9ff
color7                  #bbc2cf
color8                  #5b6268
color9                  #ff6c6b
color10                 #98be65
color11                 #ecbe7b
color12                 #51afef
color13                 #c678dd
color14                 #6be8ff
color15                 #dfe2eb

cursor                  #528bff
cursor_text_color       #282c34

url_color               #51afef

active_tab_foreground   #282c34
active_tab_background   #51afef
inactive_tab_foreground #bbc2cf
inactive_tab_background #1c1f24
