# ~/Systems/dotfiles/tools/distrobox/distrobox.ini

[dev]
image=registry.fedoraproject.org/fedora:latest
pull=true
pkg_mgr=dnf
additional_packages="golang gh php php-cli python3 python3-pip rust cargo git elixir erlang nodejs neovim lazygit tree-sitter-cli gcc gcc-c++ make"
init=false
# Pass the shell variable directly to the podman creation environment
additional_flags="--env SHELL=/bin/bash"

[private]
image=docker.io/library/debian:stable
pull=true
pkg_mgr=apt
additional_packages="curl wget ca-certificates xdg-utils zenity wl-clipboard"
init=false
additional_flags="--env SHELL=/bin/bash"

[ai]
image=registry.fedoraproject.org/fedora:latest
pull=true
pkg_mgr=dnf
additional_packages="wl-clipboard"
init=false
additional_flags="--env SHELL=/bin/bash"

[security]
image=docker.io/library/debian:stable
pull=true
pkg_mgr=apt
additional_packages="clamav rkhunter lynis"
init=false
additional_flags="--env SHELL=/bin/bash"

[pentest]
image=docker.io/library/debian:stable
pull=true
pkg_mgr=apt
additional_packages="whatweb nmap sqlmap hydra john hashcat ffuf gobuster"
init=false
additional_flags="--env SHELL=/bin/bash --env MANPAGER=less"

[notifub]
image=registry.fedoraproject.org/fedora:latest
pull=true
pkg_mgr=dnf
additional_packages="gcc make automake autoconf ncurses-devel openssl-devel inotify-tools git curl postgresql-server postgresql-contrib libstdc++-devel"
init=true
additional_flags="--env SHELL=/bin/bash"
