tap "adoptopenjdk/openjdk"
tap "filosottile/musl-cross"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazydocker"
tap "joshmedeski/sesh"
tap "kevwil/patches"
tap "libsql/sqld"
tap "neovim/neovim"
tap "nickolasburr/pfa"
tap "nikitabobko/tap"
tap "oven-sh/bun"
tap "romkatv/powerlevel10k"
tap "sergiobenitez/osxct"
tap "shivammathur/php"
tap "stripe/stripe-cli"
tap "symfony-cli/tap"
tap "tursodatabase/tap"
tap "wpscanteam/tap"
# Search tool like grep, but optimized for programmers
brew "ack"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Library for command-line editing
brew "readline"
# Next-generation aircrack with lots of new features
brew "aircrack-ng"
# Automatic configure script builder
brew "autoconf"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# C library of Git core methods that is re-entrant and linkable
brew "libgit2@1.7"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Platform built on V8 to build network applications
brew "node"
# Cryptography and SSL/TLS Toolkit
brew "openssl@1.1"
# Package manager for the web
brew "bower"
# Perl compatible regular expressions library with a new API
brew "pcre2"
# OpenType text shaping engine
brew "harfbuzz"
# Versatile and fast Unicode/ASCII/ANSI graphics renderer
brew "chafa"
# Cross-platform make
brew "cmake"
# Console Matrix
brew "cmatrix"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Generic library support script
brew "libtool"
# General-purpose scripting language
brew "php", link: false
# Dependency Manager for PHP
brew "composer"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Reimplementation of ctags(1)
brew "ctags"
# Lightweight DNS forwarder and DHCP server
brew "dnsmasq"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Compression/decompression library aiming for high speed
brew "snappy"
# Functional metaprogramming aware language built on Erlang VM
brew "elixir"
# Perl lib for reading and writing EXIF metadata
brew "exiftool"
# Database of public exploits and corresponding vulnerable software
brew "exploitdb"
# Modern, maintained replacement for ls
brew "eza"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# VP8/VP9 video codec
brew "libvpx"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Fast web fuzzer written in Go
brew "ffuf"
# Fast and simple Node.js version manager
brew "fnm"
# Monitor a directory for changes and run a shell command
brew "fswatch"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU compiler collection
brew "gcc"
# GitHub command-line tool
brew "gh"
# Interpreter for PostScript and PDF
brew "ghostscript"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Command-line option parsing utility
brew "gnu-getopt"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# X.509 and CMS library
brew "libksba"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# Directory/file & DNS busting tool written in Go
brew "gobuster"
# JavaScript Task Runner
brew "grunt-cli"
# Command-line utility for Gulp
brew "gulp-cli"
# Improved top (interactive process viewer)
brew "htop"
# Apache HTTP server
brew "httpd"
# Network logon cracker which supports many services
brew "hydra"
# GNU utilities for networking
brew "inetutils"
# Enhanced version of john, a UNIX password cracker
brew "john-jumbo"
# Image manipulation library
brew "jpeg"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Simple terminal UI for git commands
brew "lazygit"
# Conversion library
brew "libiconv"
# YAML Parser
brew "libyaml"
# Curses-based tool for viewing and analyzing log files
brew "lnav"
# Open source relational database management system
brew "mysql-client"
# NCurses Disk Usage
brew "ncdu"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Utility for managing network connections
brew "netcat"
# Web server scanner
brew "nikto"
# Port scanning utility for large networks
brew "nmap"
# Retrieves currently playing media, and simulates media actions
brew "nowplaying-cli"
# Command-line Git information tool
brew "onefetch"
# OCaml package manager
brew "opam"
# Development kit for the Java programming language
brew "openjdk"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Highly capable, feature-rich programming language
brew "perl"
# Tool to automatically fix PHP coding standards issues
brew "php-cs-fixer"
# General-purpose scripting language
brew "php@8.1"
# General-purpose scripting language
brew "php@8.2", restart_service: true, link: true
# PHP Static Analysis Tool
brew "phpstan"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Object-relational database system
brew "postgresql@14"
# Framework for managing multi-language pre-commit hooks
brew "pre-commit"
# Hook preloader
brew "proxychains-ng"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Cross-platform application and UI framework
brew "qt"
# Ruby version manager
brew "rbenv"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Rust toolchain installer
brew "rustup"
# Penetration testing for SQL injection and database servers
brew "sqlmap"
# Cross-shell prompt for astronauts
brew "starship"
# Simplified and community-driven man pages
brew "tldr"
# Terminal multiplexer
brew "tmux"
# Anonymizing overlay network for TCP
brew "tor"
# Watch files and take action when they change
brew "watchman"
# Extensible IRC client
brew "weechat"
# Internet file retriever
brew "wget"
# Command-line interface for WordPress
brew "wp-cli"
# Bash completion for Wpcli
brew "wp-cli-completion"
# JavaScript package manager
brew "yarn"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# Programming language designed for robustness, optimality, and clarity
brew "zig"
# Network scanner for Internet-wide network studies
brew "zmap"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"
# Linux cross compilers based on musl libc
brew "filosottile/musl-cross/musl-cross"
# A simple terminal UI for docker, written in Go
brew "jesseduffield/lazydocker/lazydocker"
# Smart terminal session manager
brew "joshmedeski/sesh/sesh"
# x86_64 Linux GNU Toolchain
brew "sergiobenitez/osxct/x86_64-unknown-linux-gnu"
# General-purpose scripting language
brew "shivammathur/php/php@7.4", link: true
# Stripe CLI utility
brew "stripe/stripe-cli/stripe"
# Symfony CLI helps Symfony developers manage projects, from local code to remote infrastructure
brew "symfony-cli/tap/symfony-cli"
brew "tursodatabase/tap/turso"
# Black box WordPress vulnerability scanner
brew "wpscanteam/tap/wpscan"
# Tool to flash OS images to SD cards & USB drives
cask "balenaetcher"
# Web browser focusing on privacy
cask "brave-browser"
# Web security testing toolkit
cask "burp-suite"
# Server and cloud storage browser
cask "cyberduck"
# App to build and share containerised applications and microservices
cask "docker"
# Launcher for *Epic Games* games
cask "epic-games"
# Collaborative team software
cask "figma"
cask "font-hack-nerd-font"
cask "font-monaspace"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# HTTP and GraphQL Client
cask "insomnia"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# JetBrains tools manager
cask "jetbrains-toolbox"
# Open-source keystroke visualiser
cask "keycastr"
# Free cross-platform office suite, fresh version
cask "libreoffice"
# Penetration testing framework
cask "metasploit"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# VPN client for secure internet access and private browsing
cask "nordvpn"
# Open-source software for live streaming and screen recording
cask "obs"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Client program for the OpenVPN Access Server
cask "openvpn-connect"
# Administration and development platform for PostgreSQL
cask "pgadmin4"
# Imaging utility to install operating systems to a microSD card
cask "raspberry-pi-imager"
# MySQL/MariaDB database management
cask "sequel-ace"
# Instant messaging application focusing on security
cask "signal"
# Native GUI tool for relational databases
cask "tableplus"
# Web browser focusing on security
cask "tor-browser"
# Virtualiser for x86 hardware
cask "virtualbox"
# Remote desktop application focusing on security
cask "vnc-viewer"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm"
# Native desktop client for WhatsApp
cask "whatsapp"
# Network protocol analyzer
cask "wireshark"
