# DO NOT EDIT THIS FILE
# duplicate this file in zsh/config/zshalias
# to enable/add your own custom configuration

############################
# Editor alias
############################

# use nvim, but don't make me think about it
alias vim="stty stop '' -ixoff; nvim"
alias emacs="vim"

alias sbl="sublime ."
alias subl="sublime"