# DO NOT EDIT THIS FILE
# duplicate this file in zsh/custom/
# to enable/add your own custom configuration


############################
# Laravel alias
############################
alias art='run_laravel_artisan'   
alias artg="art list | grep"
alias artr="art route:list"
alias artrg="art route:list | grep"
alias artmr="art migrate:refresh"
alias artmrs="art migrate:refresh --seed"
# Do building magic of project with actual dependency checks
alias build="build_project_assets"
# Do watching magic of project with actual dependency checks
alias watch="watch_project_assets"
# Get all translations from app and resourses
alias arttg="art translations:find && art translations:import"
# Clean all translations
alias arttc="art translations:clean"
# Export translations
alias artte="art translations:export"
# Start the queue worker once
alias artqw="art queue:work --once"


############################
# Artisan functions
############################
function art() {
    _artisan=`_artisan_find`

    if [ "$_artisan" = "" ]; then
        >&2 echo "Artisan: You seem to have upset the delicate internal balance of my housekeeper."
        return 1
    fi

    _artisan_start_time=`date +%s`
    php $_artisan $*
    _artisan_exit_status=$? # Store the exit status so we can return it later

    if [[ $1 = "make:"* && $ARTISAN_OPEN_ON_MAKE_EDITOR != "" ]]; then
        # Find and open files created by artisan
        _artisan_laravel_path=`dirname $_artisan`
        find \
            "$_artisan_laravel_path/app" \
            "$_artisan_laravel_path/tests" \
            "$_artisan_laravel_path/database" \
            -type f \
            -newermt "-$((`date +%s` - $_artisan_start_time + 1)) seconds" \
            -exec $ARTISAN_OPEN_ON_MAKE_EDITOR {} \; 2>/dev/null
    fi

    return $_artisan_exit_status
}

compdef _artisan_add_completion art

function _artisan_find() {
    # Look for artisan up the file tree until the root directory
    dir=.
    until [ $dir -ef / ]; do
        if [ -f "$dir/artisan" ]; then
            echo "$dir/artisan"
            return 0
        fi

        dir+=/..
    done

    return 1
}

function _artisan_add_completion() {
    if [ "`_artisan_find`" != "" ]; then
        compadd `_artisan_get_command_list`
    fi
}

function _artisan_get_command_list() {
    art --raw --no-ansi list | sed "s/[[:space:]].*//g"
}