# DO NOT EDIT THIS FILE
# duplicate this file in zsh/custom/
# to enable/add your own custom configuration

### PHP Unit
alias phpunit='$(get_phpunit_install)'

### Composer
alias ci='composer install'
alias cu='composer update'
alias cda="composer dump-autoload"