# DO NOT EDIT THIS FILE
# duplicate this file in zsh/custom/
# to enable/add your own custom configuration

############################
# Searching all the things
############################
alias brlg="brew list | ack"
alias cigr="composer info | ack"
alias ciggr="composer global info | ack"
alias hg='history | ack'
alias ag='alias | ack'


# Make searching through previous commands more sane
# We bind up and down arrow keys to search the history
# forward or backward.
bindkey '\e[A' history-search-backward
bindkey '\e[B' history-search-forward