# DO NOT EDIT THIS FILE
# duplicate this file in zsh/custom/
# to enable/add your own custom configuration

alias wpcu='wp core update'
alias wppu='wp plugin update --all'
alias wptu='wp theme update --all'
alias wplu='wp language core update && wp language plugin update --all && wp language theme update --all'