alias dockers='open -a Docker'
alias dcrm='docker rm $(docker ps -a -q)'
alias dcirm='docker rmi $(docker images -q)'
alias dcw='docker-compose exec workspace bash'
alias dcs='docker-compose stop'
alias dcu='docker-compose up -d'
