# DO NOT EDIT THIS FILE
# duplicate this file in zsh/custom/
# to enable/add your own custom configuration

#############################
# System Alias
#############################
source $ZSH/plugins/docker.zsh
source $ZSH/plugins/editors.zsh
source $ZSH/plugins/search.zsh
source $ZSH/plugins/system.zsh
source $ZSH/plugins/tmux.zsh

#############################
# Coding plugins
#############################

# Source control
source $ZSH/plugins/development/git.zsh
source $ZSH/plugins/development/development.zsh

# Languages
source $ZSH/plugins/development/python/python.zsh
source $ZSH/plugins/development/php/php.zsh

# Frameworks
source $ZSH/plugins/development/laravel/laravel.zsh
source $ZSH/plugins/development/drupal/drupal.zsh
source $ZSH/plugins/development/wordpress/wp-cli.zsh

#############################
# System plugins
#############################
source $ZSH/plugins/clipboard.zsh
source $ZSH/plugins/completion.zsh
source $ZSH/plugins/history.zsh
source $ZSH/plugins/z.sh
source $ZSH/plugins/extract.zsh
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
