alias ta='tmux attach'
alias tls='tmux ls'
alias tat='tmux attach -t'
alias tns='tmux new-session -s'
alias tmx='sh $MODULES/tmux/sessions/tm.sh'
# alias tmux-sessionizer='sh $MODULES/tmux/sessions/tmux-sessionizer.sh'
