# DO NOT EDIT THIS FILE
# duplicate this file in zsh/custom/
# to enable/add your own custom configuration

############################
# Drupal development alias
############################
alias drush_ulist="drush pm-list --status='Not installed' --no-core"
alias drush_list="drush pm-list"
alias drush_enlist="drush pm-list --status='Enabled' --no-core"
alias drush_dis="drush pm-uninstall"
alias drush='$(get_drush_install)'

# Checks if drush is installed in vendor folder or if we should use global one.
function get_drush_install() {
    if [ -f  vendor/drush/drush/drush ]; then
        echo './vendor/drush/drush/drush'
    else
        echo 'drush'
    fi
}