command_timeout = 9000

format = """
 $directory\
 $git_branch\
 $git_commit\
 $git_status\
 $docker_context\
 $package\
 $elixir\
 $golang\
 $lua\
 $ocaml\
 $php\
 $python\
 $ruby\
 $rust\
 $zig\
 $nodejs\
 $cmd_duration\
 $line_break\
 $status\
 $shell\
 $character"""

right_format = """
$hostname\
$localip\
$battery\
$memory_usage\
$line_break\
"""

[character]
success_symbol = '[](bold blue)'
error_symbol = '[](bold red)'
vimcmd_symbol = '[](bold green)'
vimcmd_replace_one_symbol = '[](bold purple)'
vimcmd_replace_symbol = '[](bold purple)'
vimcmd_visual_symbol = '[](bold yellow)'
disabled = false

[hostname]
disabled = false
ssh_only = true
style = "bold yellow"

[package]
format = '[🎁 $version](208 bold) '

[git_branch]
symbol = ""
truncation_length = 20
truncation_symbol = "…/"
style = 'bold dimmed purple'
format = '[$symbol $branch ]($style)'
disabled = false

[git_status]
conflicted = '⚔️ x ${count} '
ahead = '🏎💨 x ${count} '
behind = '🐢 x ${count} '
diverged = '😵 x ${count} '
up_to_date = '✓ '
untracked = '🤷x ${count} '
stashed = '📦 '
modified = '🎯x ${count} '
staged = '😵x ${count} '
renamed = '👅 '
deleted = '🗑 x ${count} '
style = 'bold dimmed red'
format = '[$all_status$ahead_behind]($style)'
disabled = false

[git_commit]
commit_hash_length = 5
tag_symbol = ' 🏷  '
only_detached = false
tag_disabled = false
style = 'bold dimmed red'
format = '[\($hash$tag\)]($style) '
disabled = false

[localip]
ssh_only = true
format = '[$localipv4](bold dimmed green) '
disabled = false

[line_break]
disabled = false

[cmd_duration]
min_time = 1000
format = ' underwent [$duration](bold yellow)'
disabled = true

# Configure Directory Path
[directory]
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false
style = 'bold blue'
read_only_style = "197"
read_only = "  "
format = "[$path]($style)[$read_only]($read_only_style) "

[memory_usage]
symbol = "󰍛 "
disabled = true
threshold = -1
style = 'bold dimmed green'

[battery]
full_symbol = '🔋 '
charging_symbol = '⚡️ '
disabled = true

[[battery.display]] # 'bold red' style and discharging_symbol when capacity is between 0% and 20%
threshold = 20
style = 'bold red'
discharging_symbol = '💀 '

[[battery.display]] # 'bold yellow' style and 💦 symbol when capacity is between 10% and 50%
threshold = 50
style = 'bold yellow'
discharging_symbol = '💦 '

[[battery.display]] # 'bold dimmed green' style and 💦 symbol when capacity is between 50% and 100%
threshold = 100
style = 'bold dimmed green'
discharging_symbol = '💦 '

[shell]
zsh_indicator = '🐚'
fish_indicator = '🐟'
style = 'bold purple'
disabled = false

[docker_context]
symbol = "🐳"
style = 'bold blue'
format = '[$symbol $context]($style) '
disabled = false

[elixir]
symbol = "💧 "
style = 'bold red'
format = '[$symbol$version]($style) '
disabled = false

[golang]
symbol = "🐹 "
style = 'bold blue'
format = '[$symbol$version]($style) '
disabled = false

[lua]
symbol = "🌙 "
style = 'bold cyan'
format = '[$symbol$version]($style) '
disabled = false

[nodejs]
symbol = " "
style = 'bold green'
version_format = 'v${raw}'
detect_extensions = ['js', 'mjs', 'cjs', 'ts', 'mts', 'cts']
detect_files = ['package.json', '.node-version']
detect_folders = ['node_modules']
format = '[$symbol$version]($style) '
disabled = false

[ocaml]
symbol = "🐫 "
style = 'bold yellow'
format = '[$symbol$version]($style) '
disabled = false

[php]
symbol = "🐘 "
style = 'bold purple'
format = '[$symbol$version]($style) '
disabled = false

[python]
symbol = "🐍 "
style = 'bold green'
format = '[$symbol$version]($style) '
disabled = false

[ruby]
symbol = "💎 "
style = 'bold red'
format = '[$symbol$version]($style) '
disabled = false

[rust]
symbol = "🦀 "
style = 'bold red'
format = '[$symbol$version]($style) '
disabled = false

[zig]
symbol = " "
style = 'bold yellow'
format = '[$symbol$version]($style) '
disabled = false
